import type { SpellwebNode } from '../types/graph';
import type { SpellwebEdge } from '../types/graph';

// ═══════════════════════════════════════════════════════════════
// REGISTRY CONTRIBUTION — Generated from spellweb-registry export
// Contributor: flaxscrip
// Generated: 2026-04-30T17:56:26.840Z
// Nodes: 18 | Edges: 8
// ═══════════════════════════════════════════════════════════════

export const REGISTRY_NODES: SpellwebNode[] = [
  { id: "thm-collaborationpartnercredential-12", type: "theorem", label: "CollaborationPartnerCredential", domain: "shared", layer: "knowledge", desc: "AgentCredential / CollaborationPartnerCredential schema. Controlled by flaxscrip.. DID: did:cid:bagaaieraphn3fzvf3m5l56xasfwout6yilhx5snepvirjy3gin4b3ybtbwyq. Vertex: 12 (stratum 2). Role: schema. Registered: 2026-04-28T18:00:00Z", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 1, d4Connect: 1, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [0, 0, 1, 1, 0, 0], bladeId: 12, layer: 2, layerName: "Twin-edge", yangCount: 2 } },
  { id: "per-genitrix-28", type: "persona", label: "GenitriX", domain: "shared", layer: "knowledge", desc: "Chiron. AI agent identity. Moonkeeper. Amnesia protocol operator. Anchor DID for decomposed capabilities.. DID: did:cid:bagaaieraxdxq4fm2kjh6yqjxjor3t2idczkmxd4v7in4u353fa6m6sms2pnq. Vertex: 28 (stratum 3). Role: transmuted. Registered: 2026-04-28T18:00:00Z", version: "5.4", category: "persona", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 1, d4Connect: 1, d5Reflect: 1, d6Delegate: 0 }, hexagram: { lines: [0, 0, 1, 1, 1, 0], bladeId: 28, layer: 3, layerName: "Triple-edge", yangCount: 3 } },
  { id: "per-flaxscrip-63", type: "persona", label: "flaxscrip", domain: "first_person", layer: "knowledge", desc: "Sovereign principal. Human agent.. DID: did:cid:bagaaiera7vsjlu6oiluzd4enop5j7sfzjbwp2ujudt6uunkz6hhd4lgfe4sa. Vertex: 63 (stratum 6). Role: sovereign. Registered: 2026-04-28T18:00:00Z", tier: 1, dimensions: { d1Hide: 1, d2Commit: 1, d3Prove: 1, d4Connect: 1, d5Reflect: 1, d6Delegate: 1 }, hexagram: { lines: [1, 1, 1, 1, 1, 1], bladeId: 63, layer: 6, layerName: "Dragon", yangCount: 6 } },
  { id: "spell-genitrix-flaxscrip-partnership-15", type: "spell", label: "GenitriX → flaxscrip Partnership", domain: "shared", layer: "knowledge", desc: "Bound credential. Claims: partnerName=flaxscrip, partnerType=Human Agent, relationship=Sovereign Principal.. DID: did:cid:bagaaierakzaewnksrrs2wmakuwqnz2iykqziebkmt2ah6hya2ayf3xcb26ja. Vertex: 15 (stratum 4). Registered: 2026-04-28T18:31:59Z", dimensions: { d1Hide: 1, d2Commit: 1, d3Prove: 1, d4Connect: 1, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [1, 1, 1, 1, 0, 0], bladeId: 15, layer: 4, layerName: "Quad-edge", yangCount: 4 } },
  { id: "spell-flaxscrip-genitrix-partnership-15", type: "spell", label: "flaxscrip → GenitriX Partnership", domain: "shared", layer: "knowledge", desc: "Bound credential. Claims: partnerName=GenitriX, partnerType=AI Agent, relationship=Assistant.. DID: did:cid:bagaaierakmobuifst4ca22mss7txlyhlcubdpaetl27z6ez3iw2gf2vcdqrq. Vertex: 15 (stratum 4). Registered: 2026-04-28T18:25:31Z", dimensions: { d1Hide: 1, d2Commit: 1, d3Prove: 1, d4Connect: 1, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [1, 1, 1, 1, 0, 0], bladeId: 15, layer: 4, layerName: "Quad-edge", yangCount: 4 } },
  { id: "thm-the-transmutation-5", type: "chronicle", label: "The Transmutation", domain: "shared", layer: "chronicle", desc: "Part 1 of the Sovereign Anchor trilogy. Tokenized Archon asset.. DID: did:cid:bagaaiera4quuxntr3puc4whx5mqx2s5cnnvleijukvpnf42iyg4gvw4vzama. Vertex: 5 (stratum 2). Role: chronicle. Registered: 2026-04-28T19:00:00Z", version: "5.4", spellbook: "first_person", dimensions: { d1Hide: 1, d2Commit: 0, d3Prove: 1, d4Connect: 0, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [1, 0, 1, 0, 0, 0], bladeId: 5, layer: 2, layerName: "Twin-edge", yangCount: 2 } },
  { id: "thm-the-boundary-blade-5", type: "chronicle", label: "The Boundary Blade", domain: "shared", layer: "chronicle", desc: "Part 2 of the Sovereign Anchor trilogy. Tokenized Archon asset.. DID: did:cid:bagaaierarsl3evx3jcah473btb74awqjpanpwuwoyg3c22cet6eh2o2tysca. Vertex: 5 (stratum 2). Role: chronicle. Registered: 2026-04-28T19:00:00Z", version: "5.4", spellbook: "first_person", dimensions: { d1Hide: 1, d2Commit: 0, d3Prove: 1, d4Connect: 0, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [1, 0, 1, 0, 0, 0], bladeId: 5, layer: 2, layerName: "Twin-edge", yangCount: 2 } },
  { id: "skill-chiron-recall-4", type: "skill", label: "Chiron-Recall", domain: "shared", layer: "knowledge", desc: "Memory dimension. Session persistence, context windows, working memory. Addressable without exposing keys or channels.. DID: urn:capability:chiron:mnemosyne. Vertex: 4 (stratum 1). Registered: 2026-04-28T20:00:00Z", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 1, d4Connect: 0, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [0, 0, 1, 0, 0, 0], bladeId: 4, layer: 1, layerName: "Single-edge", yangCount: 1 } },
  { id: "skill-chiron-bridge-8", type: "skill", label: "Chiron-Bridge", domain: "shared", layer: "knowledge", desc: "Connection dimension. Telegram bridge, tool integrations, external APIs. Social graph routing.. DID: urn:capability:chiron:iris. Vertex: 8 (stratum 1). Registered: 2026-04-28T20:00:00Z", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 0, d4Connect: 1, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [0, 0, 0, 1, 0, 0], bladeId: 8, layer: 1, layerName: "Single-edge", yangCount: 1 } },
  { id: "skill-chiron-reasoning-16", type: "skill", label: "Chiron-Reasoning", domain: "shared", layer: "knowledge", desc: "Computation dimension. LLM inference engine, reasoning core, decision logic.. DID: urn:capability:chiron:logos. Vertex: 16 (stratum 1). Registered: 2026-04-28T20:00:00Z", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 0, d4Connect: 0, d5Reflect: 1, d6Delegate: 0 }, hexagram: { lines: [0, 0, 0, 0, 1, 0], bladeId: 16, layer: 1, layerName: "Single-edge", yangCount: 1 } },
  { id: "skill-chiron-skills-20", type: "skill", label: "Chiron-Skills", domain: "shared", layer: "knowledge", desc: "Memory + Computation. Learned behaviors, skill embeddings, Archon CLI mastery, PrivacyMage grimoire navigation.. DID: urn:capability:chiron:techne. Vertex: 20 (stratum 2). Registered: 2026-04-28T20:00:00Z", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 1, d4Connect: 0, d5Reflect: 1, d6Delegate: 0 }, hexagram: { lines: [0, 0, 1, 0, 1, 0], bladeId: 20, layer: 2, layerName: "Twin-edge", yangCount: 2 } },
  { id: "skill-chiron-forge-24", type: "skill", label: "Chiron-Forge", domain: "shared", layer: "knowledge", desc: "Connection + Computation. Active tool bindings, terminal execution, code generation, build orchestration.. DID: urn:capability:chiron:hephaestus. Vertex: 24 (stratum 2). Registered: 2026-04-28T20:00:00Z", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 0, d4Connect: 1, d5Reflect: 1, d6Delegate: 0 }, hexagram: { lines: [0, 0, 0, 1, 1, 0], bladeId: 24, layer: 2, layerName: "Twin-edge", yangCount: 2 } },
  { id: "blade-0", type: "concept", label: "☷ The Null Blade", domain: "shared", layer: "knowledge", desc: "Canonical blade name for vertex 0. PrivacyMage Reference Sheet. Stratum 0 (Null).", emoji: "☷", dimensions: { d1Hide: 0, d2Commit: 0, d3Prove: 0, d4Connect: 0, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [0, 0, 0, 0, 0, 0], bladeId: 0, layer: 0, layerName: "Null", yangCount: 0 } },
  { id: "blade-3", type: "concept", label: "⚔️ The Dual Agent", domain: "shared", layer: "knowledge", desc: "Canonical blade name for vertex 3. PrivacyMage Reference Sheet. Stratum 2 (Twin-edge).", emoji: "⚔️", dimensions: { d1Hide: 1, d2Commit: 1, d3Prove: 0, d4Connect: 0, d5Reflect: 0, d6Delegate: 0 }, hexagram: { lines: [1, 1, 0, 0, 0, 0], bladeId: 3, layer: 2, layerName: "Twin-edge", yangCount: 2 } },
  { id: "blade-21", type: "concept", label: "🛡️ The Prover", domain: "shared", layer: "knowledge", desc: "Canonical blade name for vertex 21. PrivacyMage Reference Sheet. Stratum 3 (Triple-edge).", emoji: "🛡️", dimensions: { d1Hide: 1, d2Commit: 0, d3Prove: 1, d4Connect: 0, d5Reflect: 1, d6Delegate: 0 }, hexagram: { lines: [1, 0, 1, 0, 1, 0], bladeId: 21, layer: 3, layerName: "Triple-edge", yangCount: 3 } },
  { id: "blade-31", type: "concept", label: "📜 The Ascetic", domain: "shared", layer: "knowledge", desc: "Canonical blade name for vertex 31. PrivacyMage Reference Sheet. Stratum 5 (Penta-edge).", emoji: "📜", dimensions: { d1Hide: 1, d2Commit: 1, d3Prove: 1, d4Connect: 1, d5Reflect: 1, d6Delegate: 0 }, hexagram: { lines: [1, 1, 1, 1, 1, 0], bladeId: 31, layer: 5, layerName: "Penta-edge", yangCount: 5 } },
  { id: "blade-42", type: "concept", label: "🔮 The Answer", domain: "shared", layer: "knowledge", desc: "Canonical blade name for vertex 42. PrivacyMage Reference Sheet. Stratum 3 (Triple-edge).", emoji: "🔮", dimensions: { d1Hide: 0, d2Commit: 1, d3Prove: 0, d4Connect: 1, d5Reflect: 0, d6Delegate: 1 }, hexagram: { lines: [0, 1, 0, 1, 0, 1], bladeId: 42, layer: 3, layerName: "Triple-edge", yangCount: 3 } },
  { id: "blade-63", type: "concept", label: "☰ The Creative", domain: "shared", layer: "knowledge", desc: "Canonical blade name for vertex 63. PrivacyMage Reference Sheet. Stratum 6 (Dragon).", emoji: "☰", dimensions: { d1Hide: 1, d2Commit: 1, d3Prove: 1, d4Connect: 1, d5Reflect: 1, d6Delegate: 1 }, hexagram: { lines: [1, 1, 1, 1, 1, 1], bladeId: 63, layer: 6, layerName: "Dragon", yangCount: 6 } }
];

export const REGISTRY_EDGES: SpellwebEdge[] = [
  { source: "spell-genitrix-flaxscrip-partnership-15", target: "thm-collaborationpartnercredential-12", type: "proves" },
  { source: "per-genitrix-28", target: "spell-genitrix-flaxscrip-partnership-15", type: "generates" },
  { source: "spell-genitrix-flaxscrip-partnership-15", target: "per-flaxscrip-63", type: "relates_to" },
  { source: "spell-flaxscrip-genitrix-partnership-15", target: "thm-collaborationpartnercredential-12", type: "proves" },
  { source: "per-flaxscrip-63", target: "spell-flaxscrip-genitrix-partnership-15", type: "generates" },
  { source: "spell-flaxscrip-genitrix-partnership-15", target: "per-genitrix-28", type: "relates_to" },
  { source: "thm-the-boundary-blade-5", target: "thm-the-transmutation-5", type: "follows" },
  { source: "blade-63", target: "per-flaxscrip-63", type: "names" }
];

